main_host = https://xmart.deploy-test.xiaopeng.com
##  拷贝以下域名覆盖上面的，重启生效
##生产    https://xmart.xiaopeng.com
##内侧    https://10.0.13.28:8553
##预发布  https://xmart.deploy-test.xiaopeng.com
##自定义  https://自定义.com
##国际版预发布	https://xmart-eu.deploy-test.xiaopeng.com